from . import freight_booking
from . import freight_billing
from . import freight_billing_line
from . import freight_catalog_airline
from . import freight_catalog_container
from . import freight_catalog_incoterm
from . import freight_catalog_port
from . import freight_catalog_stage
from . import freight_catalog_vessel
from . import res_partner
from . import sale_order
from . import freight_debit_note
from . import freight_debit_note_item
from . import freight_credit_note
from . import freight_credit_note_item
