from . import freight_booking
from . import freight_billing
from . import freight_billing_line
from . import freight_catalog_airline
from . import freight_catalog_container
from . import freight_catalog_incoterm
from . import freight_catalog_port
from . import freight_catalog_stage
from . import freight_catalog_vehicle_supplier
from . import freight_catalog_vessel
from . import hr_employee
from . import hr_employee_public
from . import hr_expense
from . import res_partner
from . import res_users
from . import restrict_menu
from . import sale_order
from . import sale_order_line
from . import purchase
from . import purchase_order_line
from . import freight_debit_note
from . import freight_debit_note_item
from . import freight_credit_note
from . import freight_credit_note_item
from . import product
from . import product_pricelist
from . import account_move
from . import crm_lead
from . import freight_form_wo
from . import freight_form_wo_line